name: "Copy Release to Public RAP CoP Repo"
on:
  #   release:
  #     types: [published]
  workflow_dispatch:

jobs:
  push-release:
    runs-on: "ubuntu-latest"
    if: github.repository == 'josephwilson8-nhs/test_publish_from'
    steps:
      - name: Checkout private
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.EXTERNAL_REPO_TOKEN }}
          path: private
        #   fetch-depth: 0

      - name: Read the release name and create a branch. Push branch to private.
        run: |
          cd private
          echo RELEASE_NAME=$(gh release view --json name | jq -r '.name') >> $GITHUB_ENV
          echo RELEASE_BRANCH=release/${{ env.RELEASE_NAME }} >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.EXTERNAL_REPO_TOKEN }}

      #    git branch $RELEASE_BRANCH
      #    git push -u origin $RELEASE_BRANCH
      # - run: echo $GITHUB_WORKSPACE

      - run: |
          echo ${{ env.RELEASE_NAME}}
          echo ${{ env.RELEASE_BRANCH }}

      # - name: Delete .git folder from private
      #   run: |
      #     cd private
      #     ls -la
      #     rm -rf .git
      #     ls -la

      # - name: Checkout public
      #   uses: actions/checkout@v3
      #   with:
      #     token: ${{ secrets.EXTERNAL_REPO_TOKEN }}
      #     repository: josephwilson8-nhs/test_publish_to
      #     path: public

      # - name: Delete contents of public (apart from .git folder)
      #   run: |
      #     cd public
      #     ls -la
      #     find . -maxdepth 1 \( ! -name . -a ! -name .git \) -exec rm -fr {} +
      #     ls -la

      # - name: Copy contents of private to public
      #   run: |
      #     echo $PWD
      #     cp -r private/. public/
      #     cd public
      #     ls -la
      #     git status

      # - run: ls -la

      # - name: Add the public repository as a remote
      #   run: |
      #     git remote add public https://github.com/josephwilson8-nhs/test_publish_to.git
      #     git remote -v

      #     git push -u public $RELEASE_BRANCH
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.EXTERNAL_REPO_TOKEN }}
