# name: hello world workflow
# on:
#   push:
#     branches:
#     - release/*
# jobs:
#   create_pr:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Say Hello World
#         run: echo Hello World
