on:
  push:
    branches:
    - release/*
name: hello world workflow
jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello World
        run: echo Hello World
      
      - uses: actions/checkout@v3
        
      - name: Print Branch name
        run: echo $GITHUB_REF
