name: 'Push Release to Public RAP CoP Repo'
on:
  release:
    types: [published]
  workflow_dispatch:
    

jobs:
  push-release:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Read the release name and create a branch
        run: |
          RELEASE_NAME=$(gh release view v0.0.1 --json name | jq -r '.name')
          git checkout -b release/$RELEASE_NAME
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

