name: "Pull in release branch"

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "[echo] or execute"
        default: "echo"
      branch:
        description: "branch to pull in"
        required: true

jobs:
  echo-branch:
    if: ${{ github.event.inputs.mode }} = "echo"
    runs-on: ubuntu-latest
    steps:
    - name: "echo dispatch"
      run: echo "${{ github.event.inputs.branch }}"