name: "Pull in release branch"

on:
  repository_dispatch:
    types: [release_event]

jobs:
  echo-branch:
    runs-on: ubuntu-latest
    steps:
    - name: "echo dispatch"
      run: echo "${{ github.event.client_payload.branch }}"

  pull-branch:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v3

    - name: "pull release branch in"
      run: |
        git remote add private https://github.com/josephwilson8-nhs/test_publish_to
        git fetch private ${{ github.event.client_payload.branch }}
        git checkout -b ${{ github.event.client_payload.branch }} private/${{ github.event.client_payload.branch }}
        git push -u origin ${{ github.event.client_payload.branch }}
 