name: "Pull in release branch"

on:
  repository_dispatch:
    types: [release_event]

jobs:
  echo-branch:
    runs-on: ubuntu-latest
    steps:
    - name: "echo dispatch"
      run: echo "${{ github.event.client_payload.branch }}"