name: "Pull in release branch"

on:
  repository_dispatch:
    types: [release_event]

jobs:
  echo-branch:
    runs-on: ubuntu-latest
    steps:
    - name: "echo dispatch"
      run: echo "${{ github.event.client_payload.branch }}"

  pull-branch:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout code"
      uses: actions/checkout@v3

    - name: "add private repository as remote"
      run: |
        git remote add private https://github.com/josephwilson8-nhs/test_publish_from
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: "Fetch release branch from private"
      run: |
        git fetch private ${{ github.event.client_payload.branch }}
    - name: "Create a new branch based of the private release branch"
      run: |
        git checkout -b ${{ github.event.client_payload.branch }} private/${{ github.event.client_payload.branch }}
    - name: "Push new release branch to origin"
      run: |
        git push origin ${{ github.event.client_payload.branch }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
